version: "3"
services:
  client:
    image: climbing-tracker-client
    build: ./client
    restart: unless-stopped
    ports:
      - "8000:80"
    links:
      - server
    networks:
      - webappnetwork
  server:
    image: climbing-tracker-server
    build: ./server
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    networks:
      - webappnetwork
    environment:
      - SERVER_PORT=9000
      - DATABASE_URL=mongodb://mongodb:27017/climbing-tracker
  mongodb:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - webappnetwork
volumes:
  mongodb-data:
networks:
  webappnetwork:
    driver: bridge
